name: Build e Deploy Package

on:
  push:
  branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with: 
          dotnet-version: '6.0.x'

      - name: Compilar o projeto
        run: dotnet build --configuration Release

      - name: Testar o projeto
        run: dotnet test

      - name: Criar o pacote
        run: dotnet pack --configuration Release

      - name: Publicar o pacote
        run: dotnet nuget push "MoneyExtension/bin/Release/*.nupkg" -k ${{secrets.NUGET_TOKEN}} -s https://api.nuget.org/v3/index.json