name: Build e Deploy Package

on:
  push:
  branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
          with:
            dotnet-version: '6.0.x'
      - name: Build with Dotnet
        run: dotnet build --configuration Release

      - name: Test Extensions
        run: dotnet test

      - name: Create the Package
        run: dotnet pack --configuration Release

      - name: Publish package
        run: dotnet nuget push "MoneyExtension/bin/Release/*.nupkg" -k ${{secrets.NUGET_TOKEN}} -s https://api.nuget.org/v3/index.json